name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ubuntu:hirsute
    env:
      DEBIAN_FRONTEND: "noninteractive"
    strategy:
      fail-fast: false
      matrix:
        config:
          - { cc: clang, cxx: clang++ }
          - { cc: gcc,   cxx: g++ }
    steps:
      - name: Update package lists
        run: apt update -qq
      - name: Install tools and dependencies
        run: >-
          apt install -y
          clang
          cmake
          gcc
          g++
          libfmt-dev
          libgtest-dev
          ninja-build
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure CMake
        run: >-
          cmake .
          -Bbuild
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }}
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
          -DCOEL_BUILD_EXAMPLE=ON
          -DCOEL_BUILD_TESTS=ON
          -GNinja
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: ./build/coel-tests
