name: Code Style
on: [push, pull_request]
jobs:
  clang-format:
    name: Clang Format
    runs-on: ubuntu-latest
    container: ubuntu:hirsute
    env:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - name: Update package lists
        run: apt update -qq
      - name: Install tools
        run: >-
          apt install -y
          clang-format
          git
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run clang-format
        shell: bash
        run: |
          find . -name '*.cc' -or -name '*.hh' | xargs clang-format -i
          git diff | tee format-diff
          if [ -s format-diff ]; then exit 1; fi
